codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "60...90"

status:
  project:
    default:
      threshold: 0.2%
      target: 52.03%
  patch:
    default:
      target: 52.03%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

