inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
Metrics/ParameterLists:
  Exclude:
    - 'script/regression_test_single_account.rb'
Layout/LineLength:
  Exclude:
    - 'script/regression_test_single_account.rb'
