hostname:      <%= ENV["BONNIE_HOSTNAME"] %> 
smtp_hostname: <%= ENV["SMTP_HOSTNAME"] %>
smtp_port:     <%= ENV["SMTP_PORT"] %>
smtp_username: <%= ENV["SMTP_USERNAME"] %>
smtp_password: <%= ENV["SMTP_PASSWORD"] %>
smtp_tls:      <%= ENV["SMTP_TLS"] %>

virus_scan:
  enabled: false
  scan_url: 'http://localhost:5000/scan-file'
  api_key: '3953b0d6-820e-4e7b-af77-f08b6cf281ba'
  timeout: 30


