@DataElementCategories = class DataElementCategories
  @CATEGORIES: {
    "CapabilityStatement": "conformance",
    "StructureDefinition": "conformance",
    "ImplementationGuide": "conformance",
    "SearchParameter": "conformance",
    "MessageDefinition": "conformance",
    "OperationDefinition": "conformance",
    "CompartmentDefinition": "conformance",
    "StructureMap": "conformance",
    "GraphDefinition": "conformance",
    "ExampleScenario": "conformance",
    "CodeSystem": "terminology",
    "ValueSet": "terminology",
    "ConceptMap": "terminology",
    "NamingSystem": "terminology",
    "TerminologyCapabilities": "terminology",
    "Provenance": "security",
    "AuditEvent": "security",
    "Consent": "security",
    "Composition": "documents",
    "DocumentManifest": "documents",
    "DocumentReference": "documents",
    "CatalogEntry": "documents",
    "Basic": "other",
    "Binary": "other",
    "Bundle": "other",
    "Linkage": "other",
    "MessageHeader": "other",
    "OperationOutcome": "other",
    "Parameters": "other",
    "Subscription": "other",
    "Patient": "individuals",
    "Practitioner": "individuals",
    "PractitionerRole": "individuals",
    "RelatedPerson": "individuals",
    "Person": "individuals",
    "Group": "individuals",
    "Organization": "providers entities",
    "OrganizationAffiliation": "providers entities",
    "HealthcareService": "providers entities",
    "Endpoint": "providers entities",
    "Location": "providers entities",
    "Substance": "material entities",
    "BiologicallyDerivedProduct": "material entities",
    "Device": "material entities",
    "DeviceMetric": "material entities",
    "Task": "workflow",
    "Appointment": "workflow",
    "AppointmentResponse": "workflow",
    "Schedule": "workflow",
    "Slot": "workflow",
    "VerificationResult": "workflow",
    "Encounter": "management",
    "EpisodeOfCare": "management",
    "Flag": "management",
    "List": "management",
    "Library": "management",
    "AllergyIntolerance": "clinical summary",
    "AdverseEvent": "clinical summary",
    "Condition": "clinical summary",
    "Procedure": "clinical summary",
    "FamilyMemberHistory": "clinical summary",
    "ClinicalImpression": "clinical summary",
    "DetectedIssue": "clinical summary",
    "Observation": "diagnostics",
    "Media": "diagnostics",
    "DiagnosticReport": "diagnostics",
    "Specimen": "diagnostics",
    "BodyStructure": "diagnostics",
    "ImagingStudy": "diagnostics",
    "QuestionnaireResponse": "diagnostics",
    "MolecularSequence": "diagnostics",
    "MedicationRequest": "medications",
    "MedicationAdministration": "medications",
    "MedicationDispense": "medications",
    "MedicationStatement": "medications",
    "Medication": "medications",
    "MedicationKnowledge": "medications",
    "Immunization": "medications",
    "ImmunizationEvaluation": "medications",
    "ImmunizationRecommendation": "medications",
    "CarePlan": "care provision",
    "CareTeam": "care provision",
    "Goal": "care provision",
    "ServiceRequest": "care provision",
    "NutritionOrder": "care provision",
    "VisionPrescription": "care provision",
    "RiskAssessment": "care provision",
    "RequestGroup": "care provision",
    "Communication": "request response",
    "CommunicationRequest": "request response",
    "DeviceRequest": "request response",
    "DeviceUseStatement": "request response",
    "GuidanceResponse": "request response",
    "SupplyRequest": "request response",
    "SupplyDelivery": "request response",
    "Coverage": "financial support",
    "CoverageEligibilityRequest": "financial support",
    "CoverageEligibilityResponse": "financial support",
    "EnrollmentRequest": "financial support",
    "EnrollmentResponse": "financial support",
    "Claim": "billing",
    "ClaimResponse": "billing",
    "Invoice": "billing",
    "PaymentNotice": "payment",
    "PaymentReconciliation": "payment",
    "Account": "general",
    "ChargeItem": "general",
    "ChargeItemDefinition": "general",
    "Contract": "general",
    "ExplanationOfBenefit": "general",
    "InsurancePlan": "general",
    "ResearchStudy": "public health research",
    "ResearchSubject": "public health research",
    "ActivityDefinition": "definitional artifacts",
    "DeviceDefinition": "definitional artifacts",
    "EventDefinition": "definitional artifacts",
    "ObservationDefinition": "definitional artifacts",
    "PlanDefinition": "definitional artifacts",
    "Questionnaire": "definitional artifacts",
    "SpecimenDefinition": "definitional artifacts",
    "ResearchDefinition": "evidence-based medicine",
    "ResearchElementDefinition": "evidence-based medicine",
    "Evidence": "evidence-based medicine",
    "EvidenceVariable": "evidence-based medicine",
    "EffectEvidenceSynthesis": "evidence-based medicine",
    "RiskEvidenceSynthesis": "evidence-based medicine",
    "Measure": "quality reporting testing",
    "MeasureReport": "quality reporting testing",
    "TestScript": "quality reporting testing",
    "TestReport": "quality reporting testing",
    "MedicinalProduct": "medication definition",
    "MedicinalProductAuthorization": "medication definition",
    "MedicinalProductContraindication": "medication definition",
    "MedicinalProductIndication": "medication definition",
    "MedicinalProductIngredient": "medication definition",
    "MedicinalProductInteraction": "medication definition",
    "MedicinalProductManufactured": "medication definition",
    "MedicinalProductPackaged": "medication definition",
    "MedicinalProductPharmaceutical": "medication definition",
    "MedicinalProductUndesirableEffect": "medication definition",
    "SubstanceNucleicAcid": "medication definition",
    "SubstancePolymer": "medication definition",
    "SubstanceProtein": "medication definition",
    "SubstanceReferenceInformation": "medication definition",
    "SubstanceSpecification": "medication definition",
    "SubstanceSourceMaterial": "medication definition"
  }